### PR TITLE
Style the flags select for empty/inactive values in translated_row

### PR DESCRIPTION
**Pull request by jtomaszewski**
Fixes https://github.com/fabn/activeadmin-globalize/issues/2 .

### CODE REVIEW

**Comment by fabn** [comment]
@jtomaszewski this commit seems good, did you tried it in a local environment? Are you using master versions of Globalize and Active Admin?

The only issue I see is that this PR is missing some specs, I'd like to have them before merging.

Are you able to write some specs for this feature? I understand that you might not be able to run current specs on your machine even if [last build was green](https://travis-ci.org/fabn/activeadmin-globalize/builds/129412480), so if you try and fail please report and I'll try to help you.

**Comment by fabn** [comment]
I see that your PR in #17 is build with green status on Travis (just some warnings), so this failure it's not an issue with newer versions of dependencies but with this PR itself.

You should try to fix them and to implement a test for this feature before I can accept this change.

**Comment by jtomaszewski** [comment]
Yeah, give me a day or two and I'll make the specs. Both commits seems to be working for me on development and staging.

**Comment by jtomaszewski** [comment]
Specs fixed and pushed with --force to this PR branch.

**Comment by fabn** [comment]
Good, merging this. 

Thanks for your contribution.

**Pull request merged**
